---
version: '3.8'

services:
  # cds-status-app:
  #   build:
  #     context: .
  #     dockerfile: dockerfile.yaml
  #     args:
  #       RUNNER_VERSION: '2.312.0'
  #   environment:
  #     GH_TOKEN: ${GH_TOKEN}
  #     GH_OWNER: ${GH_OWNER}
  #     GH_REPOSITORY: 'cds.status.app'
  # cds-terminal-app:
  #   build:
  #     context: .
  #     dockerfile: dockerfile.yaml
  #     args:
  #       RUNNER_VERSION: '2.312.0'
  #   environment:
  #     GH_TOKEN: ${GH_TOKEN}
  #     GH_OWNER: ${GH_OWNER}
  #     GH_REPOSITORY: 'cds.terminal.app'
  natedresume:
    user: "1000"
    build:
      context: .
      dockerfile: dockerfile.yaml
      args:
        RUNNER_VERSION: '2.312.0'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: 'natedresume'
